export enum TransactionType {
  WELCOME_BONUS = "WELCOME_BONUS",
  DAILY_LOGIN = "DAILY_LOGIN",
  SPIN_REWARD = "SPIN_REWARD",
  TASK_REWARD = "TASK_REWARD",
  REFERRAL_REWARD = "REFERRAL_REWARD",

  DEPOSIT = "DEPOSIT",
  WITHDRAW = "WITHDRAW",

  TRANSFER_IN = "TRANSFER_IN",
  TRANSFER_OUT = "TRANSFER_OUT",

  ADMIN_ADD = "ADMIN_ADD",
  ADMIN_REMOVE = "ADMIN_REMOVE",

  WITHDRAW_REQUEST = "WITHDRAW_REQUEST",
  WITHDRAW_APPROVED = "WITHDRAW_APPROVED",
  WITHDRAW_REJECTED = "WITHDRAW_REJECTED",
  
}